// Auto-generated file - DO NOT EDIT
// This file is automatically generated by the generate-routes script

const express = require('express');
const router = express.Router();

// Import all route files
const activityLogRoutes = require('./activity-logs.routes');
const authRoutes = require('./auth.routes');
const authUtilsRoutes = require('./auth-utils.routes');
const baseRoutes = require('./base.routes');
const branchesRoutes = require('./branches.routes');
const campaignRoutes = require('./campaign.routes');
const cashbackRoutes = require('./cashback.routes');
const categoriesRoutes = require('./categories.routes');
const customerCategoryRoutes = require('./customer-categories.routes');
const commonPdfRoutes = require('./common-pdf.routes');
const couponRoutes = require('./coupon.routes');
const creditRoutes = require('./credit.routes');
const customersRoutes = require('./customers.routes');
const dashboardRoutes = require('./dashboard.routes');
const easyTableRoutes = require('./easy-tables.routes');
const expensesRoutes = require('./expenses.routes');
const installRoutes = require('./install.routes');
const invoicesRoutes = require('./invoices.routes');
const itemsRoutes = require('./items.routes');
const onlineOrderingRoutes = require('./online-ordering.routes');
const loyaltyRoutes = require('./loyalty.routes');
const messagingRoutes = require('./messaging.routes');
const purchaseOrdersRoutes = require('./purchase-orders.routes');
const quotesRoutes = require('./quotes.routes');
const receivingsRoutes = require('./receivings.routes');
const handsetsRoutes = require('./handsets.routes');
const registersRoutes = require('./registers.routes');
const rolesRoutes = require('./roles.routes');
const authorizationsRoutes = require('./authorizations.routes');
const shiftsRoutes = require('./shifts.routes');
const salesRoutes = require('./sales.routes');
const settingsRoutes = require('./settings.routes'); // Note: File not renamed, but route will be /settings
const settingsGroupsRoutes = require('./settings-groups.routes');
const clientErrorsRoutes = require('./client-errors.routes');
const stockLogsRoutes = require('./stock-logs.routes');
const suppliersRoutes = require('./suppliers.routes');
const usersRoutes = require('./users.routes'); // Updated from userRoutes
const recoveryRoutes = require('./recovery.routes');
const variantsRoutes = require('./variants.routes');
const whatsappRoutes = require('./whatsapp.routes');

// Root endpoint for /api
router.get('/', (req, res) => {
  res.status(200).json({
    type: 'success',
    message: 'API v2',
    data: null,
  });
});

/*
 * The access grid, enforced - for API keys only.
 *
 * Each route file protects itself, so req.user is already set by the time a
 * handler runs; this sits in front of all of them and refuses anything the
 * key's own grid does not permit. It does nothing at all for a session, whose
 * requests never set req.isApiKey: turning enforcement on for the tills in the
 * same change would risk locking a shop out of its own counter over a route
 * mapped wrongly, which deserves its own testing rather than a free ride on
 * this one.
 */
const { enforceApiKeyAcl } = require('../middleware/api-key');
router.use(enforceApiKeyAcl);

// Mount routes with consistent naming
router.use('/activity-logs', activityLogRoutes);
router.use('/auth', authRoutes);
router.use('/auth-utils', authUtilsRoutes);
router.use('/base', baseRoutes);
router.use('/branches', branchesRoutes);
router.use('/categories', categoriesRoutes);
router.use('/campaigns', campaignRoutes);
router.use('/cashback', cashbackRoutes);
router.use('/coupons', couponRoutes);
router.use('/credit', creditRoutes);
router.use('/customer-category', customerCategoryRoutes);
router.use('/customercategory', customerCategoryRoutes); // Legacy PHP path support
router.use('/common-pdf', commonPdfRoutes);
router.use('/customers', customersRoutes);
router.use('/dashboard', dashboardRoutes); // Removed /api prefix for consistency
router.use('/easy-table', easyTableRoutes);
router.use('/expenses', expensesRoutes);
router.use('/install', installRoutes);
router.use('/invoices', invoicesRoutes);
router.use('/items', itemsRoutes);
router.use('/online-ordering', onlineOrderingRoutes);
router.use('/loyalty', loyaltyRoutes);
router.use('/messaging', messagingRoutes);
router.use('/purchaseOrders', purchaseOrdersRoutes);
router.use('/quotes', quotesRoutes);
router.use('/receivings', receivingsRoutes);
router.use('/handsets', handsetsRoutes);
router.use('/registers', registersRoutes);
router.use('/roles', rolesRoutes);
router.use('/authorizations', authorizationsRoutes);
router.use('/shifts', shiftsRoutes);
router.use('/sales', salesRoutes);
// Unauthenticated by design - the errors worth hearing about happen before
// auth works. See the route file for how the surface is held small.
router.use('/client-errors', clientErrorsRoutes);
router.use('/settings/group', settingsGroupsRoutes);
router.use('/settings', settingsRoutes); // Primary path
router.use('/setting', settingsRoutes); // Legacy PHP path support
router.use('/stock-logs', stockLogsRoutes); // Changed from stocklogs to stock-logs
router.use('/stocklogs', stockLogsRoutes); // Legacy path support
router.use('/suppliers', suppliersRoutes);
router.use('/users/recovery', recoveryRoutes);
router.use('/users', usersRoutes);
router.use('/variants', variantsRoutes);
router.use('/whatsapp', whatsappRoutes);

module.exports = router;
