name: Auto Deploy to Test Server

# Controls when the action will run.
on:
  push:
    # On which branch
    branches: ["main"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job name
  build:
    # Runner name
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
      # Sets up node
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: gulp build

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.FRONTEND_TEST_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.FRONTEND_TEST_S3_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FRONTEND_TEST_S3_KEY }}
          AWS_REGION: 'ap-south-1'   # optional: defaults to us-east-1
          SOURCE_DIR: 'public'      # optional: defaults to entire repository
