const winston = require('winston');
const { createLogger, format, transports } = winston;
const { combine, timestamp, printf, colorize, json, errors } = format;
const path = require('path');
const fs = require('fs');
const DailyRotateFile = require('winston-daily-rotate-file');

// Create logs directory if it doesn't exist
const logDir = 'logs';
if (!fs.existsSync(logDir)) {
  fs.mkdirSync(logDir);
}

// Custom log format for console
const consoleFormat = printf(({ level, message, timestamp, stack, ...meta }) => {
  let log = `${timestamp} [${level}]: ${message}`;

  if (stack) {
    log += '\n' + stack;
  }

  if (Object.keys(meta).length > 0) {
    log += '\n' + JSON.stringify(meta, null, 2);
  }

  return log;
});

// Custom log format for files
const fileFormat = printf(({ level, message, timestamp, stack, ...meta }) => {
  const log = {
    timestamp,
    level,
    message,
    ...(stack && { stack }),
    ...(Object.keys(meta).length > 0 && { meta }),
  };

  return JSON.stringify(log);
});

// Custom error formatter
const errorFormatter = format((info) => {
  if (info instanceof Error) {
    return {
      ...info,
      message: info.message,
      stack: info.stack,
    };
  }

  if (info.error && info.error instanceof Error) {
    return {
      ...info,
      message: info.message || info.error.message,
      stack: info.error.stack,
      code: info.error.code,
    };
  }

  return info;
});

/*
 * Keep one logged event on one line.
 *
 * Anything a shop or a customer typed can end up in a log message - a product
 * name, an email, a search term - and a newline inside one of those splits the
 * entry in two. The second half then looks like a separate event, and it can
 * be made to look like any event the attacker chooses: a forged "login
 * succeeded" line sitting between two real ones, in the file we read when we
 * are working out what happened.
 *
 * These logs are local files read by us during support rather than fed to
 * anything that acts on them, so the damage is a misleading support session
 * rather than a breach. That is still worth one line here, and one line here
 * is better than the forty-six edits CodeQL would otherwise have us make at
 * every call site - which would also have to be remembered at every future one.
 *
 * Escaped rather than stripped: a genuine newline in a customer's address is
 * information, and turning it into \n keeps it readable without letting it
 * break the record apart. Stack traces are exempt because their newlines are
 * the point, and they are ours rather than anybody's input.
 */
/* eslint-disable-next-line no-control-regex -- matching control characters
   is the entire point: they are what breaks a log line apart. */
const CONTROL_CHARS = /[\r\n\u2028\u2029\x00-\x08\x0b\x0c\x0e-\x1f]/g;
const ESCAPES = { '\r': '\\r', '\n': '\\n', '\u2028': '\\u2028', '\u2029': '\\u2029' };
const flatten = (value) =>
  typeof value === 'string' ? value.replace(CONTROL_CHARS, (c) => ESCAPES[c] || '') : value;

const oneLinePerEvent = format((info) => {
  info.message = flatten(info.message);
  for (const key of Object.keys(info)) {
    /* The stack is multi-line on purpose, and it is generated by Node rather
       than supplied by a request. */
    if (key === 'stack') continue;
    info[key] = flatten(info[key]);
  }
  return info;
});

// Create logger instance
const logger = createLogger({
  level: process.env.NODE_ENV === 'production' ? 'info' : 'debug',
  format: combine(
    timestamp({ format: 'YYYY-MM-DD HH:mm:ss' }),
    errors({ stack: true }),
    errorFormatter(),
    /* Last, so it also covers anything the formatters above introduced. */
    oneLinePerEvent()
  ),
  defaultMeta: { service: 'express-api' },
  transports: [
    // Console transport for development
    new transports.Console({
      format: combine(colorize(), consoleFormat),
      level: 'debug',
    }),

    // Daily rotate file transport for all logs
    new DailyRotateFile({
      filename: path.join(logDir, 'application-%DATE%.log'),
      datePattern: 'YYYY-MM-DD',
      zippedArchive: true,
      maxSize: '20m',
      maxFiles: '14d',
      format: combine(json(), fileFormat),
    }),

    // Error logs
    new DailyRotateFile({
      filename: path.join(logDir, 'error-%DATE%.log'),
      datePattern: 'YYYY-MM-DD',
      zippedArchive: true,
      maxSize: '20m',
      maxFiles: '30d',
      level: 'error',
      format: combine(json(), fileFormat),
    }),
  ],
  exceptionHandlers: [
    new transports.File({
      filename: path.join(logDir, 'exceptions.log'),
      format: combine(json(), fileFormat),
    }),
  ],
  exitOnError: false,
});

// Create a stream for morgan (HTTP request logging)
logger.stream = {
  write: (message) => {
    logger.info(message.trim());
  },
};

// Request logging middleware
const requestLogger = (req, res, next) => {
  logger.http('Incoming Request', {
    method: req.method,
    url: req.originalUrl,
    ip: req.ip,
    userAgent: req.get('user-agent'),
    body: req.body,
    query: req.query,
    params: req.params,
  });

  // Log response when it's finished
  const originalSend = res.send;
  res.send = function (body) {
    logger.http('Outgoing Response', {
      statusCode: res.statusCode,
      url: req.originalUrl,
      response: body,
    });
    return originalSend.call(this, body);
  };

  next();
};

// Error logging middleware
const errorLogger = (err, req, res, next) => {
  logger.error('Unhandled Error', {
    error: {
      message: err.message,
      stack: err.stack,
      name: err.name,
      ...err,
    },
    request: {
      method: req.method,
      url: req.originalUrl,
      body: req.body,
      query: req.query,
      params: req.params,
      user: req.user ? { id: req.user.id, email: req.user.email } : undefined,
    },
  });

  next(err);
};

// Promise rejection handler
process.on('unhandledRejection', (reason, promise) => {
  logger.error('Unhandled Rejection at:', { promise, reason });
});

// Uncaught exception handler
process.on('uncaughtException', (error) => {
  logger.error('Uncaught Exception:', error);
  // In production, you might want to gracefully shut down the server
  if (process.env.NODE_ENV === 'production') {
    process.exit(1);
  }
});

module.exports = {
  logger,
  requestLogger,
  errorLogger,
};
