# Bake the thermal font into the repository.
#
# WHY THIS IS A SCRIPT AND NOT A FUNCTION
#
# A strike-through on a thermal roll has to be drawn as dots (see
# src/escpos-raster-text.js for why there is no other way), and drawing dots
# means having glyphs. The till cannot render text: there is no canvas in the
# Electron main process, and going through a hidden window is the 1,114 ms step
# the kitchen ticket was moved off in the first place.
#
# So the glyphs are rendered ONCE, here, and committed. The table travels with
# the app, which also means every shop's ticket looks the same rather than
# depending on which fonts that particular Windows happens to have.
#
# Run by hand on Windows when the shape of the type is deliberately changed:
#
#   powershell -ExecutionPolicy Bypass -File scripts/build-escpos-font.ps1
#
# CI cannot run it - an Ubuntu runner has no Consolas - so the output is
# checked in and tests assert on the table rather than regenerating it.
#
# THE NUMBERS, AND WHERE THEY CAME FROM
#
# Font A on an 80mm roll is a 12 x 24 dot cell. The first attempt at this asked
# for 17.5px type, one glyph per 12 dots, and the owner said on paper: "text is
# small". 17.5px is the EM BOX, not the letter - the capitals landed about 11
# dots against the printer's own 17.
#
# 28px matches the capital. At 28px Consolas advances 15.4 dots, which will not
# fit a 12 dot cell, so the glyphs are drawn at full height and squeezed
# sideways. Condensed letters at the right height read far better than correct
# letters at the wrong one, which is the thing four rounds of paper settled.
#
# Regular weight, not bold, and a threshold of 640 out of 765: both chosen off
# the roll rather than on screen.

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$CellW = 12
$CellH = 24
$FontPx = 28.0
$Threshold = 640      # of 765; how much ink survives the one-bit conversion
$First = 0x20         # space
$Last = 0xff          # the top of WPC1252, which is the code page the app sets

$outFile = Join-Path (Split-Path -Parent $PSScriptRoot) 'src\escpos-font-a.json'

# One strip holding every glyph, so the face is measured and scaled once.
$count = $Last - $First + 1
$bmp = New-Object System.Drawing.Bitmap ($CellW * $count), $CellH
$g = [System.Drawing.Graphics]::FromImage($bmp)
$g.Clear([System.Drawing.Color]::White)
$g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::SingleBitPerPixelGridFit

$font = New-Object System.Drawing.Font 'Consolas', $FontPx, ([System.Drawing.FontStyle]::Regular), ([System.Drawing.GraphicsUnit]::Pixel)

# Measured rather than assumed, so the squeeze is right for whatever metrics
# this machine's Consolas actually has.
$fmt = [System.Drawing.StringFormat]::GenericTypographic
$probe = $g.MeasureString('MMMMMMMMMM', $font, [int]10000, $fmt)
$advance = $probe.Width / 10.0
$sx = $CellW / $advance

# WPC1252 is what the app selects with ESC t 16, so a byte has to mean the same
# character here as it will on the roll.
$enc = [System.Text.Encoding]::GetEncoding(1252)

$state = $g.Save()
$g.ScaleTransform($sx, 1.0)
for ($i = 0; $i -lt $count; $i++) {
    $ch = $enc.GetString([byte[]]@([byte]($First + $i)))
    # -2 lifts the em box so the cap height sits in the cell; the descender
    # space below is not worth losing it for.
    $g.DrawString($ch, $font, [System.Drawing.Brushes]::Black, ($i * $CellW / $sx), -2, $fmt)
}
$g.Restore($state)
$g.Dispose()

# Two bytes a row, 12 bits used, most significant bit leftmost - the same order
# GS v 0 wants, so a glyph is copied into a raster without shuffling.
$glyphBytes = $CellH * 2
$data = New-Object byte[] ($count * $glyphBytes)
$ink = 0
for ($i = 0; $i -lt $count; $i++) {
    for ($y = 0; $y -lt $CellH; $y++) {
        $hi = 0; $lo = 0
        for ($x = 0; $x -lt $CellW; $x++) {
            $p = $bmp.GetPixel($i * $CellW + $x, $y)
            if (($p.R + $p.G + $p.B) -lt $Threshold) {
                $ink++
                if ($x -lt 8) { $hi = $hi -bor (1 -shl (7 - $x)) }
                else { $lo = $lo -bor (1 -shl (7 - ($x - 8))) }
            }
        }
        $data[$i * $glyphBytes + $y * 2] = $hi
        $data[$i * $glyphBytes + $y * 2 + 1] = $lo
    }
}
$bmp.Dispose()

$json = [ordered]@{
    note = 'Generated by scripts/build-escpos-font.ps1. Do not edit by hand.'
    face = 'Consolas'
    fontPx = $FontPx
    threshold = $Threshold
    cellWidth = $CellW
    cellHeight = $CellH
    firstByte = $First
    lastByte = $Last
    encoding = 'windows-1252'
    glyphs = [Convert]::ToBase64String($data)
} | ConvertTo-Json

# UTF8 without a BOM: the repo's tests read these as plain JSON.
[System.IO.File]::WriteAllText($outFile, $json, (New-Object System.Text.UTF8Encoding $false))

Write-Output ("{0}`n  {1} glyphs, {2}x{3} cell, {4} bytes of table, {5} dots of ink" -f `
    $outFile, $count, $CellW, $CellH, $data.Length, $ink)
Write-Output ("  Consolas {0}px advances {1:N2}, squeezed by {2:N3}" -f $FontPx, $advance, $sx)
